version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/app
    environment:
      - TWITCH_STREAM_KEY=${TWITCH_STREAM_KEY}
      - ROM_PATH=${ROM_PATH}
    command: python -m unittest discover -s tests -p 'test_*.py'
