services:
  agent:
    build: .
    command: python -m src.main
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY:-}
      - ENABLE_GUI=${ENABLE_GUI:-true}
      - PYTHONPATH=/app/src
    ports:
      - "5001:5000"
      - "5555:5555"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
