version: '3.9'
services:
  agent:
    build: .
    command: python -m src.main
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "5555:5555"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
